{
 "title": "Home Server Monitor - UPS",
 "tags": [
  "home-server-monitor",
  "provisioned",
  "v7.2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"storage_status\" WITH KEY = \"host\""
   },
   {
    "name": "ups_name",
    "label": "UPS",
    "query": "SHOW TAG VALUES FROM \"ups_status\" WITH KEY = \"ups_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "UPS status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"status_code\") AS \"UPS status\" FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "UPS load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"load_percent\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "UPS temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"internal_temp\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"battery_voltage\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "Battery charge (estimated)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"battery_charge_estimated\") AS \"Charge\" FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "Input voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"input_voltage\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "Output voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"output_voltage\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "Input frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"input_frequency\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "UPS information",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "query": "SELECT last(\"battery_voltage\"), last(\"battery_charge_estimated\"), last(\"internal_temp\"), last(\"raw_status\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY \"host\",\"ups_name\",\"model\",\"serial\",\"status\""
    }
   ]
  },
  {
   "title": "Input / output voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Input",
     "query": "SELECT mean(\"input_voltage\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Output",
     "query": "SELECT mean(\"output_voltage\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "UPS load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Load",
     "query": "SELECT mean(\"load_percent\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "UPS temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperature",
     "query": "SELECT mean(\"internal_temp\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery voltage",
     "query": "SELECT mean(\"battery_voltage\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Battery charge (estimated by voltage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Estimated charge",
     "query": "SELECT mean(\"battery_charge_estimated\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Input frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Frequency",
     "query": "SELECT mean(\"input_frequency\") FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "UPS status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"status_code\") AS \"Status code\" FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "On battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"on_battery_code\") AS \"On battery\" FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  },
  {
   "title": "Low battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"low_battery_code\") AS \"Low battery\" FROM \"ups_status\" WHERE $timeFilter AND \"ups_name\" =~ /^$ups_name$/"
    }
   ]
  }
 ]
}